@Taxer_Web_API_HostAddress = http://localhost:5035

POST {{Taxer_Web_API_HostAddress}}/api/v1/tax/calculate
Content-Type: application/json

{
    "income": 1000000,
    "postalCode": "1000"
}

###
